export const SET_ACTIVE_EVENT = 'SET_ACTIVE_EVENT'
export const SET_USER = 'SET_USER'

export const SET_EVENT = 'SET_EVENT'
export const SET_EVENT_TALKS = 'SET_EVENT_TALKS'

export const SET_EVENTS = 'SET_EVENTS'
export const SET_SUBMITTED_TALKS = 'SET_SUBMITTED_TALKS'
